from __future__ import annotations

import time
from collections.abc import Callable
from typing import Any
from uuid import uuid4

import httpx

from app.core.config.config import Settings
from app.core.config.logging import emit_log


Sleep = Callable[[float], None]


def build_payloads(batch_id: str, batch_size: int) -> list[dict[str, str]]:
    request_types = (
        "Acceso a plataforma",
        "Soporte técnico",
        "Académica",
        "Administrativa",
    )
    priorities = ("Baja", "Media", "Alta")

    return [
        {
            "external_id": f"CONSUMER-{batch_id[:8]}-{index:03d}",
            "type": request_types[(index - 1) % len(request_types)],
            "applicant": f"Consumer Demo {index}",
            "email": f"consumer.{batch_id}.{index}@example.com",
            "description": f"Request generated by consumer batch {batch_id}",
            "priority": priorities[(index - 1) % len(priorities)],
        }
        for index in range(1, batch_size + 1)
    ]


def request_with_retry(
    client: httpx.Client,
    settings: Settings,
    method: str,
    endpoint: str,
    *,
    request_id: str,
    correlation_id: str,
    json: dict[str, Any] | None = None,
    sleep: Sleep = time.sleep,
) -> httpx.Response | None:
    max_attempts = settings.consumer_max_retries + 1

    for attempt in range(1, max_attempts + 1):
        start = time.perf_counter()
        try:
            response = client.request(method, endpoint, json=json)
        except httpx.RequestError as exc:
            is_final_attempt = attempt == max_attempts
            emit_log(
                service=settings.service_name,
                level="error" if is_final_attempt else "warning",
                message=(
                    "consumer request exhausted retries"
                    if is_final_attempt
                    else "consumer temporary connection error"
                ),
                request_id=request_id,
                correlation_id=correlation_id,
                method=method,
                endpoint=endpoint,
                elapsed_ms=(time.perf_counter() - start) * 1000,
                attempt=attempt,
                error=exc,
            )
            if is_final_attempt:
                return None
            sleep(settings.consumer_retry_delay_seconds)
            continue

        elapsed_ms = (time.perf_counter() - start) * 1000
        if response.status_code >= 500:
            is_final_attempt = attempt == max_attempts
            emit_log(
                service=settings.service_name,
                level="error" if is_final_attempt else "warning",
                message=(
                    "consumer request exhausted retries"
                    if is_final_attempt
                    else "consumer temporary server error"
                ),
                request_id=request_id,
                correlation_id=correlation_id,
                method=method,
                endpoint=endpoint,
                status_code=response.status_code,
                elapsed_ms=elapsed_ms,
                attempt=attempt,
                error=RuntimeError(f"HTTP {response.status_code}"),
            )
            if is_final_attempt:
                return response
            sleep(settings.consumer_retry_delay_seconds)
            continue

        is_client_error = 400 <= response.status_code < 500
        emit_log(
            service=settings.service_name,
            level="error" if is_client_error else "info",
            message=(
                "consumer definitive client error"
                if is_client_error
                else "consumer request completed"
            ),
            request_id=request_id,
            correlation_id=correlation_id,
            method=method,
            endpoint=endpoint,
            status_code=response.status_code,
            elapsed_ms=elapsed_ms,
            attempt=attempt,
        )
        return response

    return None  # pragma: no cover - loop always returns


def process_batch(
    client: httpx.Client,
    settings: Settings,
    *,
    batch_id: str,
    sleep: Sleep = time.sleep,
) -> tuple[int, int]:
    created_count = 0
    queried_count = 0

    for payload in build_payloads(batch_id, settings.consumer_batch_size):
        external_id = payload["external_id"]
        create_response = request_with_retry(
            client,
            settings,
            "POST",
            "/solicitudes",
            request_id=external_id,
            correlation_id=batch_id,
            json=payload,
            sleep=sleep,
        )
        if create_response is None or not create_response.is_success:
            continue

        created_count += 1
        try:
            solicitud_id = create_response.json()["id"]
        except (ValueError, KeyError, TypeError) as exc:
            emit_log(
                service=settings.service_name,
                level="error",
                message="consumer received an invalid create response",
                request_id=external_id,
                correlation_id=batch_id,
                method="POST",
                endpoint="/solicitudes",
                status_code=create_response.status_code,
                error=exc,
            )
            continue

        query_response = request_with_retry(
            client,
            settings,
            "GET",
            f"/solicitudes/{solicitud_id}",
            request_id=external_id,
            correlation_id=batch_id,
            sleep=sleep,
        )
        if query_response is not None and query_response.is_success:
            queried_count += 1

    return created_count, queried_count


def main() -> None:
    settings = Settings()
    batch_id = str(uuid4())

    with httpx.Client(
        base_url=settings.consumer_api_url.rstrip("/"),
        timeout=settings.consumer_timeout_seconds,
        headers={"X-Correlation-ID": batch_id},
    ) as client:
        created_count, queried_count = process_batch(
            client,
            settings,
            batch_id=batch_id,
        )

    emit_log(
        service=settings.service_name,
        level="info",
        message="consumer batch completed",
        correlation_id=batch_id,
        method="BATCH",
        endpoint="/solicitudes",
        status_code=200,
    )
    print(
        f"Consumer batch completed: created={created_count}, queried={queried_count}",
        flush=True,
    )


if __name__ == "__main__":
    main()
